### DISCUSSION TITLE
Data binning based on variable instead of x, y, z?

### DISCUSSION THREAD

**Discussion by BenWibking** [Alpine-DAV/ascent#1139] [Q&A] [answered]
Is it possible to do data binning based on two variables, rather than based on an axis and a variable?

What I'm looking for is just like what can be done in VisIt with the DataBinning operator, using the scripting interface to set the `dim1BasedOn`, `dim2BasedOn`, or `dim3BasedOn` attributes to a variable in the current dataset (https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/python_scripting/attributes.html?highlight=databinning#databinning-databinningattributes).

I don't see an example in the Ascent docs that does this, so maybe it's not possible in Ascent.

**Comment by cyrush** [comment, marked as answer]
Hi @BenWibking  yes this is supported. 

One constraint is that the binning vars must have the same centering (or association) to the mesh. 

So you may need to add a recenter pipeline filter if your centerings differ. 

We did not have tests that exercise or demonstrate this, so I created the following PR:

https://github.com/Alpine-DAV/ascent/pull/1140

If the details of the PR are too dense, here is the equivalent yaml example for a binning query with a recentered input: 

```
- 
  action: "add_pipelines"
  pipelines: 
    pl1: 
      f1: 
        type: "recenter"
        params: 
          field: "braid"
          association: "element"
- 
  action: "add_queries"
  queries: 
    q2: 
      params: 
        expression: "binning('radial','max', [axis('radial',num_bins=10), axis( 'braid' ,num_bins=10)])"
        name: "my_binning"
      pipeline: "pl1"
```

And here is the binning result from the ascent info:

```
100: 
  type: "binning"
  attrs: 
    value: 
      value: [0.0, 0.0, 54.5703753351875, ..., 0.0, 0.0]
      type: "array"
    reduction_var: 
      value: "radial"
      type: "string"
    reduction_op: 
      value: "max"
      type: "string"
    bin_axes: 
      value: 
        radial: 
          num_bins: 10
          clamp: 0
          min_val: 3.53479756646709
          max_val: 174.205080756888
        braid: 
          num_bins: 10
          clamp: 0
          min_val: -9.73570590456385
          max_val: 10.866867172197
    association: 
      value: "element"
      type: "string"
  time: 3.1414999961853
```

There is also a test that shows how to do this with a binning filter vs a query.
