### DISCUSSION TITLE
create directory if it does not exists

### DISCUSSION THREAD

**Discussion by indra098124** [Alpine-DAV/ascent#1276] [Q&A] [answered]
I would like to generate multiple images using an ascent yaml file and to save each scene in a separate directory. Is this possible for ascent to generate directories if they don't exists based on the path given to the image name for e.g. Ux_images/Ux_%05d?

**Comment by cyrush** [comment, marked as answer]
@indra098124  
We don't create intermediate directories, however one way to do this is using Ascent's shell command actions:

Here is an example:

```
- 
  action: "add_commands"
  commands: 
    c1: 
      params: 
        shell_command: "mkdir -p My_Dir"
        mpi_behavior: "root"
```

This will only run on MPI Task 0.

You can use a more complex shell command if you like (check for the dir and then only create)
Hope this helps,
-Cyrus
