### DISCUSSION TITLE
write data from ascent to load in paraview

### DISCUSSION THREAD

**Discussion by indra098124** [Alpine-DAV/ascent#1321] [Q&A] [answered]
Is it possible to write data using ascent in a format that can be loaded in paraview for further post-processing?

**Comment by cyrush** [comment]
With recent Ascent, you can create an extract that writes a set of legacy vtk files.

```
- action: add_extracts
   e1:
      type: "vtk"
      params:
          path: "my_output_"
```

These will be grouped by a `.visit` file. Paraview may be able to use this, if not there maybe be another paraview way to treat all of the output files as a single domain decomposed dataset.
