### DISCUSSION TITLE
image_prefix

### DISCUSSION THREAD

**Discussion by spatel81** [Alpine-DAV/ascent#1405] [General]
Hi, 

if there is a way to set the `image_prefix` in a yaml so it dumps filenames according to time rather than timestep?

for example, I have the following setup in my .yaml when rendering in-situ images using NekRS:

```
  action: "add_scenes"
  scenes:
    s2: 
      plots:
        p1: 
          type: "pseudocolor"
          field: "velocity_y"
          pipeline: "pl2"
          color_table:
            name: "Rainbow Desaturated"
          min_value: -2.5
          max_value: 2.5 
      renders:
        r1: 
          camera:
            position: [18.9475, -25.975, 30.5072]
            look_at: [0.0, -25.975, 30.5072]
            up: [0.0, 0.0, 1.0]
            zoom: 3.00
          image_prefix: "img/turbIc_x%06d"
          world_annotations: true
          screen_annotations: true
          image_width: 2048
          image_height: 256 

```
I would like the filenames to reflect the physical time (e.g. 2.01, 3.09, 4.98, etc) rather than steps (i.e. 100, 200, 300, 400, etc.). Hope this makes sense. any help would be much appreciated.
