### ISSUE TITLE
Generating unique images at distinct cycle values

### ISSUE THREAD

**Issue by bgranzow** [Alpine-DAV/ascent#1018]
Hello! I have a question about Ascent usage that I haven't been able to answer myself by looking through the documentation. I apologize if this has been documented and I've missed it.

I would like to use Ascent to generate a distinct sequence of rendered images as a simulation progresses over a number of cycles. As a simplest example, let's say I want to render images at each simulation cycle and save those images in distinct png files as: `out_image_cycle_0.png, out_image_cycle_1.png, ...`

I have implemented some simple prototyping code with ascent that I've pasted below.

```c++
conduit::Node conduit_mesh;
conduit::Node ascent_options;
/* set valid conduit_mesh inputs here */
/* set valid ascent_options inputs here */
ascent::Ascent ascent_instance;
ascent_instance.open(ascent_options);
for (int cycle = 0;  cycle < 2; ++cycle) {
  conduit_mesh["state/cycle"].set_external(&cycle);
  conduit::Node actions;
  std::string actions_string;
  /* set actions_string here by opening and parsing a file called actions.yaml */
  /* this .yaml file tells ascent to render an image to image_name: "out_ascent_cycle" */
  actions.parse(actions_string, "yaml");
  ascent_instance.execute(actions);
}
ascent_instance.close(ascent_options);

```

In this code, I am able to loop over two cycles and render an image at each cycle, however the image I render is overwritten to the file `out_image_cycle.png` at each cycle. Is there any way to let Ascent know to generate distinct images per cycle? Or would my best bet be to pre-process the actions_string before I call `actions.parse(actions_string, "yaml')` to change the `image_name:` value  to something unique at each cycle?

Hope this question makes sense. Thanks for the consideration.

example `actions.yaml` file
```yaml
- 
  action: "add_scenes"
  scenes: 
    s1: 
      plots: 
        p1: 
          type: "pseudocolor"
          field: "mass"
      renders: 
        r1: 
          camera: 
            position: [-0.6, -0.6, -0.8]
          image_name: "out_ascent_cycle"
```

**Comment by BenWibking** [comment]
You can use `image_prefix` instead. As an example:

```
-
  action: "add_scenes"
  scenes:
    s1:
      plots:
        p1:
          type: "pseudocolor"
          field: "log_gasDensity"
      renders:
        r1:
          image_prefix: "log_density%05d"
```
