### ISSUE TITLE
Contour presenting rendering artifacts, as the number of ranks increases

### ISSUE THREAD

**Issue by mvictoras** [Alpine-DAV/ascent#1022]
We have instrumented NekRS with ASCENT, and found that as the number of ranks increases, so are various rendering artifacts. Is this expected behavior?

We are on v0.8.0.

My `ascent_actions.yaml`:
```
-
  action: "add_pipelines"
  pipelines:
    pl1:
      f3:
        type: "contour"
        params:
          field: "temperature"
          iso_values: [40, 50, 60]
-
  action: "add_scenes"
  scenes:
    s1:
      plots:
        p1:
          type: "pseudocolor"
          field: "pressure"
          pipeline: "pl1"
      renders:
        r1:
          camera:
            position: [-30.32, -30.99, 34.63]
            look_at: [-0.006, -0.006, 0.932]
            up: [0.146, 0.659, 0.737]
            zoom: 2.0
          image_prefix: "pb_%04d"
```
Resulting images:

4 ranks:
![pb_0000-4ranks](https://user-images.githubusercontent.com/1523876/192055385-a1f8e202-3161-42c7-a277-f7a126c5082e.png)

40 ranks:
![pb_0000-40ranks](https://user-images.githubusercontent.com/1523876/192055392-40c15d89-5ca0-44b6-ba36-705dfc6f752e.png)
