### ISSUE TITLE
Streamlines crashing

### ISSUE THREAD

**Issue by mvictoras** [Alpine-DAV/ascent#1023]
We have instrumented NekRS with ASCENT and getting a crash when trying to use streamlines. Are they working correctly on v0.8.0?

**Comment by cyrush** [comment]
can you share the actions?

We can create streamlines, but I am not sure there are paths to render them with VTK-m (we might need a tube filter to ray trace them)

**Comment by cyrush** [comment]
Also you will need VTK-m w/ MPI support to use streamlines.

**Comment by mvictoras** [comment]
VTK-m and MPI are enabled:
```
==> Root specs
ascent@0.8.0


==> 1 installed package
-- cray-sles15-zen3 / gcc@11.2.0 --------------------------------
ascent@0.8.0
    cmake@3.23.3
        ncurses@6.3
            pkgconf@1.8.0
        openssl@1.1.1q
            ca-certificates-mozilla@2022-07-19
            perl@5.34.1
                berkeley-db@18.1.40
                bzip2@1.0.8
                    diffutils@3.8
                        libiconv@1.16
                gdbm@1.19
                    readline@8.1.2
                zlib@1.2.12
    conduit@0.8.4
        hdf5@1.12.1.3
        metis@5.1.0
        mpich@8.1.16
        parmetis@4.0.3
    vtk-h@0.8.1
        vtk-m@1.7.1
```


Here is the action file:

```
-
  action: "add_pipelines"
  pipelines:
    pl1:
      f1:
        type: "composite_vector"
        params:
          field1: "vel_x"
          field2: "vel_y"
          field3: "vel_z"
          output_name: "velocity"
      f2:
        type: "vector_magnitude"
        params:
          field: "velocity"
          output_name: "vel_mag"
      f3:
        type: "streamline"
        params:
          field: "velocity"
          num_seeds: 100
          num_steps: 1000
          step_size: 0.1
          seed_bounding_box_xmin: -5.0
          seed_bounding_box_xmax: 5.0
          seed_bounding_box_ymin: -5.0
          seed_bounding_box_ymax: 5.0
          seed_bounding_box_zmin: -5.0
          seed_bounding_box_zmax: 5.0
-
  action: "add_scenes"
  scenes:
    scene1:
      plots:
        plt1:
          type: "mesh"
          pipeline: "pl1"
```
