### ISSUE TITLE
query expression for rms of a field?

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#1121]
Is there a built-in way to do a query for the rms of a field?

This appears to be syntactically valid:
```
  action: "add_queries"
  queries:
    q3:
      params:
        expression: "pow(avg(field('drho_over_rho') * field('drho_over_rho')), 0.5)"
        name: "rms_drho"
```
but requires re-building Ascent with OCCA, which I don't want to do on every CPU/CUDA/HIP machine I'm running on:
```
[Error] Ascent::execute 
file: /Users/benwibking/ascent_build/ascent/src/libs/ascent/runtimes/ascent_expression_eval.cpp
line: 1543
message: 
Error while executing expression 'pow(avg(field('drho_over_rho') * field('drho_over_rho')), 0.5)': 
file: /Users/benwibking/ascent_build/ascent/src/libs/ascent/runtimes/expressions/ascent_expression_jit_filters.cpp
line: 652
message: 
Jit errors: 
- "\nfile: /Users/benwibking/ascent_build/ascent/src/libs/ascent/runtimes/expressions/ascent_derived_jit.cpp\nline: 1019\nmessage: \nJIT compilation for derived fields requires OCCA support but Ascent was not compiled with OCCA.\n"
```

I tried `rms(field('my_field'))`, but that doesn't work:
```
[Error] Ascent::execute 
file: /Users/benwibking/ascent_build/ascent/src/libs/ascent/runtimes/ascent_expression_eval.cpp
line: 1543
message: 
Error while executing expression 'rms(field('drho_over_rho'))': 
file: /Users/benwibking/ascent_build/ascent/src/libs/ascent/runtimes/expressions/ascent_expressions_ast.cpp
line: 584
message: 
Expressions: Unknown function 'rms'.
```
