### ISSUE TITLE
Data binning segfaults when data is in device memory on non-unified memory systems

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#1122]
Data binning works fine when running on CPU. However, when running this actions file
```
-
  action: "add_queries"
  queries:
    bin_pressure:
      params:
        expression: "binning('dP_over_P','avg', [axis('x',[-50,50]), axis('y', [-50,50]), axis('z', num_bins=64)])"
        name: dP_profile
-
  action: "save_session"
```
on A100 GPUs, I get a segmentation fault:

```
Loguru caught a signal: SIGSEGV
Stack trace:
14            0x45bc0e ./build-gpu/bin/athenaPK() [0x45bc0e]
13      0x7f3227bb8493 __libc_start_main + 243
12            0x445c1f ./build-gpu/bin/athenaPK() [0x445c1f]
11            0x737781 ./build-gpu/bin/athenaPK() [0x737781]
10            0x7df6fe ./build-gpu/bin/athenaPK() [0x7df6fe]
9             0x8c32f8 ./build-gpu/bin/athenaPK() [0x8c32f8]
8       0x7f324c485707 ascent::Ascent::execute(conduit::Node const&) + 439
7       0x7f324c4afd30 ascent::AscentRuntime::Execute(conduit::Node const&) + 1072
6       0x7f324c14d0d1 flow::Workspace::execute() + 817
5       0x7f324c66d500 ascent::runtime::filters::BasicQuery::execute() + 672
4       0x7f324c4c78ed ascent::runtime::expressions::ExpressionEval::evaluate(std::string, std::string) + 2717
3       0x7f324c14d0d1 flow::Workspace::execute() + 817
2       0x7f324c57ff8e ascent::runtime::expressions::Binning::execute() + 846
1       0x7f324c57f066 ascent::runtime::expressions::binning_interface(std::string const&, std::string const&, conduit::Node const&, conduit::Node const&, conduit::Node const&, conduit::Node&, conduit::Node&, conduit::Node&) + 2454
0       0x7f324c4ef27b ascent::runtime::expressions::binning(conduit::Node const&, conduit::Node&, std::string const&, std::string const&, double, std::string const&) + 6875
2023-03-28 12:23:58.600 (  32.416s) [main thread     ]                       :0     FATL| Signal: SIGSEGV
```

I can provide a full reproducer if needed.
