### ISSUE TITLE
PNG Metadata

### ISSUE THREAD

**Issue by WillTrojak** [Alpine-DAV/ascent#1155]
Would it be possible to add something to the scene API that allows metadata to be written to PNGs? Additionally, would it be possible for a flag that causes a map from value to colourmap colour to be written to the metadata? 

The idea of this is twofold, it would allow for PNG files to be more accurately post-processed, with the colour map being handy for training ML/dataset curation. The second thing would be to improve reproducibility, for example in PyFR we would like to write parts of the config/inifile and stats to the png.

**Comment by WillTrojak** [comment]
A similar feature is now supported in Paraview: https://www.kitware.com/paraview-state-embedded-in-png-screenshots/

**Comment by nicolemarsaglia** [comment]
This is a great idea! I had previously looked into adding more info to PNGs, but it was not as straightforward as I had hoped, so I tabled it. 

I will look into this again!

**Comment by nicolemarsaglia** [comment]
Looking into this, in the meantime, one thing Ascent does have in an info() call in the API that populates a conduit node with metadata rather than the PNG, and can be used in a similar way: https://ascent.readthedocs.io/en/latest/AscentAPI.html?highlight=info#info

**Comment by brugger1** [comment]
I added the ability to add meta data to PNGs with the following PR.

https://github.com/Alpine-DAV/ascent/pull/746

If you add specific conduit nodes under the state, it will add those strings to the PNG meta data. Specifically:

state/software
state/source
state/title
state/info
state/comment

**Comment by nicolemarsaglia** [comment]
Thanks @brugger1 

edit: Definitely needs to be documented.

**Comment by brugger1** [comment]
Yes, the PR didn't have any documentation associated with it. :(

**Comment by WillTrojak** [comment]
This is great, thanks @brugger1. I'll give it a go!

**Comment by cyrush** [comment]
@WillTrojak  if you are creating images for ML datasets, you might be interested in scalar rendering -- which you can use to save an image out to a HDF5 file and preserve the floating point data. 


https://ascent.readthedocs.io/en/latest/Actions/Examples.html?highlight=scalar#an-example-of-scalar-rendering

**Comment by WillTrojak** [comment]
I was looking into this for partitioned domains and found that the metadata implemented [here](urlhttps://github.com/Alpine-DAV/ascent/blob/e52b7bb8c9fd131f2fd49edf58037cc5ef77a166/src/libs/ascent/runtimes/ascent_main_runtime.cpp#L511) only works for flat data structures ie those such as:
```
state:
    stuff: ...
coordinates:
    x:...
```
and doesn't work for meshes that have the following form:
```
domain_1:
    state:
        domain_id: 1
        stuff: ...
    coordinates:
        x:...
domain_2:
    state:
        domain_id: 2
        stuff: ...
    coordinates:
        x:...
```
I'd be happy to implement this; however, it needs some choices to be made. For example, I think that maybe the metadata from the root rank (taken at the first child ie `m_source.child(0)`). What are the ascent team's thoughts?

**Comment by WillTrojak** [comment]
I have been looking into this for a partitioned mesh, and it seems that the current metadata implementation in #746 doesn't work on meshes with multiple domains. ie it works on
```
state:
    stuff: ...
coordinates:
    x: ...
```
but it doesn't work on:
```
domain_0:
    state:
        domain_id: 0
        stuff: ...
    coordinates:
        x: ...
domain_1:
    state:
        domain_id: 1
        stuff: ...
    coordinates:
        x: ...
```
I'd be happy to implement this, but I need a bit of direction from the ascent team. The most straightforward choice to me is to only output the metadata from the first domain child which is sort of the root rank (ie. `m_source.child(0)`) and this could be done in the PopulateMetadata function. What are your thoughts?
