### ISSUE TITLE
on GPU, ascent_ghosts is wrong in Blueprint extracts of slices perpendicular to the y-axis

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#1168]
We've noticed a render failure for slices that are exactly perpendicular to the y-axis, e.g.:
```
    y_slice_pl:
      f1:
        type: "slice"
        params:
          point:
            x: 0.5
            y: 0.125
            z: 0.125
          normal:
            x: 0.0
            y: 1.0
            z: 0.0
```

For these slices, when using Ascent to write Blueprint outputs from two different AMR codes (one using AMReX and one using Parthenon), the renders are blank.

Inspecting the Blueprint files in VisIt, it appears that the Blueprint HDF5 extracts have all the cells marked as ghost cells, i.e. `ascent_ghosts` equals 1.0 everywhere, whereas for the x-slices and z-slices the ghost cells are indicated correctly:
![AMR0004](https://github.com/Alpine-DAV/ascent/assets/1781919/3b499052-8ea8-446f-be8f-c4fecc637fa1)

The original actions file used for this case is here: 
[ascent_actions.yaml.txt](https://github.com/Alpine-DAV/ascent/files/11985383/ascent_actions.yaml.txt)

**Comment by cyrush** [comment]
@BenWibking thanks for the report, that is quite odd. 

Can you provide an extract that contains full dataset?

**Comment by BenWibking** [comment]
I'll re-run and save an extract of the full dataset, also reduce the resolution so it's a more reasonable size.

**Comment by BenWibking** [comment]
Well, this is weird. If I try to save a full extract, I get:
```
[Error] Ascent::execute
file: /projects/cvz/bwibking/ascent-0.9.2dev-cuda12/conduit-v0.8.8/src/libs/relay/conduit_relay_io_hdf5.cpp
line: 1768
message:
HDF5 Error (error code: -1, reference path: "./blueprint.cycle_009500/domain_000000.hdf5:values") Failed to write to HDF5 Dataset 360287970189656101
```

My actions file is:
```
-
  action: "add_extracts"
  extracts:
    e1:
      type: "relay"
      params:
        path: "blueprint"
        protocol: "blueprint/mesh/hdf5"
-
  action: "execute"
```
