### ISSUE TITLE
annotations conflicts with bg_color

### ISSUE THREAD

**Issue by yslan** [Alpine-DAV/ascent#1203]
I want to turn off legend, remove the bounding box, and set white background color. 

However, the setting below seems to overwrite the `bg_color`
- set 1: resulting black background
```
      renders:
        r1:
          world_annotations: false
          screen_annotations: false
          bg_color: [1.0, 1.0, 1.0]
          fg_color: [0.0, 0.0, 0.0]
```

Interestingly, if I only turn off one of the annotation, the `bg_color` will be correct, but settings both annotations off won't work.

- set 2: resulting white background
```
      renders:
        r1:
          world_annotations: false
          bg_color: [1.0, 1.0, 1.0]
          fg_color: [0.0, 0.0, 0.0]
```

- set 3: resulting white background
```
      renders:
        r1:
          screen_annotations: false
          bg_color: [1.0, 1.0, 1.0]
          fg_color: [0.0, 0.0, 0.0]
```

Speaking of background, is there anyway to get transparent background?
