### ISSUE TITLE
3slice's z_offset is not set?

### ISSUE THREAD

**Issue by yslan** [Alpine-DAV/ascent#1206]
Hi, I have a question about the 3slice filter.

My understanding is, given a point [x_offset, y_offset, z_offset], it cuts 2 slices with normal parallel to x, y, and z axis. 

However, the offset seems to do something strange. Especially the z_offset.  See the comparison below. For some reason, the z value is set to 0.

- 3slice
   ```
    pl4:
      f1:
        type: "3slice"
        params:
          x_offset: 9.773
          y_offset: 9.773
          z_offset: 0.450
   ```
   ![p5_004120](https://github.com/Alpine-DAV/ascent/assets/29413012/b3c5b71e-1ac3-42e4-955c-7c3c1fde4b11)

- 3 x slices
   ```
    pl1: # yz slice
      f1:
        type: "slice"
        params:
          point:
            x: 9.773
            y: 0.0
            z: 0.0
          normal:
            x: 1.0
            y: 0.0
            z: 0.0
    pl2: # xz slice
      f1:
        type: "slice"
        params:
          point:
            x: 0.0
            y: 9.773
            z: 0.0
          normal:
            x: 0.0
            y: 1.0
            z: 0.0
    pl3: # z-slice, outflow
      f1:
        type: "slice"
        params:
          point:
            x: 0.0
            y: 0.0
            z: 0.450
          normal:
            x: 0.0
            y: 0.0
            z: 1.0
   ```
   ![p4_004120](https://github.com/Alpine-DAV/ascent/assets/29413012/d34288c1-2845-4ba0-a111-0e713552580a)

The geometry is bounded in a box [-9.7736,9.7736] x [-9.7736,9.7736] x [0.0,0.455] and the camera location is at 
```
      renders:
        r1:
          camera:
            position: [20.0, 15.0, 10.0]
            look_at: [0.0, 0.0, 0.450]
            up: [0.0, 1.0, 0.0]
            zoom: 1.0
```
