### ISSUE TITLE
Queries not working when attached to pipeline

### ISSUE THREAD

**Issue by nicolemarsaglia** [Alpine-DAV/ascent#1253]
Workaround: Expressions should be used as queries. 

Expressions used as pipelines to make derived fields are losing the derived field for later use. i.e. make an image

**Comment by nicolemarsaglia** [comment]
![expression_as_pipeline](https://github.com/Alpine-DAV/ascent/assets/24232495/f2d0e799-1880-4077-be3b-47095dee1272)
expression as pipeline; output gets lost

**Comment by nicolemarsaglia** [comment]
expression as query; output connects to tree
![expression_as_query](https://github.com/Alpine-DAV/ascent/assets/24232495/ec1e621f-6cfc-422b-b06a-41a693b78030)

**Comment by cyrush** [comment]
@nicolemarsaglia  do you have the yaml actions for these two cases to compare?

Thinking about some overall changes to expressions and it would be helpful to stare at these.

**Comment by nicolemarsaglia** [comment]
@cyrush I have something that is a combination of the two and is making me questions my initial conclusions. Let me double check because one of the routes was definitely not working.

**Comment by nicolemarsaglia** [comment]
@cyrush alright, so I was right that my initial conclusions seemed off. But I finally recreated my query to nowhere via attaching it to a pipeline: https://ascent.readthedocs.io/en/latest/Actions/ExpressionsOverview.html#queries-on-pipeline-results

![flow_graph_query_using_pipeline_results](https://github.com/user-attachments/assets/a30ead11-2dc2-4449-a4f4-f2c41179dbda)
Image based on query is blank (with this error from Ascent: `(s1/p1) unknown field 'e_plus_one' field names: 'acceleration', 'coords', 'e', 'e_power', 'e_power_plus_two', 'elem_mass', 'forces', 'nodal_mass', 'p', 'q', 'v', 'velocity'`): 
![-180 0_0 0_e_power_plus_one](https://github.com/user-attachments/assets/5ef37bbe-f1c7-4d10-822b-d855b980e55e)
Image based on pipeline is fine: 
![-180 0_0 0_e_power_plus_2](https://github.com/user-attachments/assets/8c9cb484-af99-41fe-b170-4d4ff4452129)

Actions file: 
[query_on_pipeline_ascent_actions.txt](https://github.com/user-attachments/files/16592530/query_on_pipeline_ascent_actions.txt)

**Comment by cyrush** [comment]
```
-
  action: "add_pipelines"
  pipelines:
    pl1:
      f1: 
        type: "power_of_field"
        params:
          field: "e"
          exponent: 2.0
          output_field: "e_power"
      f2:
        type: "expression"
        params:
          expression: "field('e_power') + 2.0" 
          name: "e_power_plus_two"
-
  action: "add_queries"
  queries:
    q1:
      pipeline: "pl1"
      params:
        expression: "field('e_power')+ 1.0"
        name: "e_plus_one"
- 
  action: "add_scenes"
  scenes: 
    s1: 
      plots: 
        p1: 
          type: "pseudocolor"
          pipeline: "pl1"
          field: "e_plus_one"
      renders:
        r1:
          type: "cinema"
          phi: 1
          theta: 1
          db_name: "e_power_plus_one"
          output_path: "/home/user/ascent/build/examples/proxies/lulesh2.0.3/"
          camera:
            zoom: 1.5
    s2: 
      plots: 
        p1: 
          type: "pseudocolor"
          pipeline: "pl1"
          field: "e_power_plus_two"
      renders:
        r1:
          type: "cinema"
          phi: 1
          theta: 1
          db_name: "e_power_plus_2"
          output_path: "/home/user/ascent/build/examples/proxies/lulesh2.0.3/"
          camera:
            zoom: 1.5

```
