### ISSUE TITLE
images not saved under default_dir

### ISSUE THREAD

**Issue by yslan** [Alpine-DAV/ascent#1289]
Hi, 

I'm trying to put default images under a local folder `imgs/` (the path exists). When I follow the documentation and set it in `ascent_options.json`, every works as expected.
```
{
  "default_dir" : "/path/to/output/dir"
}
```

However, when I tried to hard code it into the interface with the folllowing line (copied from `test/t_ascent_runtime_options.cpp`), the images are saved to `pwd` instead of `$pwd/imgs`
```
ascent_opts["default_dir"] = "imgs";
```

When doing this test, I make sure there is no `ascent_options.json` and `ascent_options.yaml` in my current folder. 

I do see an error when the `default_dir` does not exist, meaning it's indeed checking the path. And, at the end, the `ascent_session.yaml` is indeed saved under `imgs/`.  For some reason, only the images do not honor the `default_dir`. My `image_prefix: "q_%06d"` is not using an absolute path.

I'm using the commit 6d1ca3f8d27e9b640be93453c6453f76f545ae7d
Can someone confirm whether there's a bug? 

Thanks,
Yu-Hsiang

**Comment by nicolemarsaglia** [comment]
Hi @yslan, thanks for pointing this out. I will investigate and get back to you!

**Comment by nicolemarsaglia** [comment]
Hi @yslan, so far I have not been able to duplicate what you are experiencing. I can, however, create this bug when I use `image_name` rather than `image_prefix` and have a fix in #1295. 

Could you share the rest of your ascent actions?

**Comment by cyrush** [comment]
@yslan  are you still hitting this issue?

**Comment by yslan** [comment]
@cyrush Yes, I still have this issue.
This runs on Polaris. Images are saved to the case folder and only the `ascent_session.yaml` is saved to `img/`

- version
   ```
   version: "0.9.2-8baa7"
   git_sha1: "8baa78c9f2f32f7e170d3281ee7168226bc3cb41"
   ```


- setup
  ```
     conduit::Node ascent_opts;
     ascent_opts["mpi_comm"] = MPI_Comm_c2f(comm);
     ascent_opts["default_dir"] = "imgs";

     nekAscent::mAscent.open(ascent_opts);
   ```
   `ascent_opts.prints()` does show `default_dir: "imgs"`
- action file
   ```
   - 
     action: "add_pipelines"
     pipelines:
       pl1:
         f1:
           type: "slice"
           params:
             point:
               x: 0.0
               y: 0.0
               z: 0.0
             normal:
               x: 1.0
               y: 0.0
               z: 0.0
   - 
     action: "add_scenes"
     scenes:
       s1:
         plots:
           p1:
             type: "pseudocolor"
             field: "scalar00"
             pipeline: "pl1"
             color_table:
               name: "Cool to Warm Extended"
             min_value: 0.0
             max_value: 1.0
         renders:
           r1:
             camera:
               azimuth: 90
               zoom: 8.0
             image_prefix: "s00_%06d"
             world_annotations: false
             screen_annotations: false
             image_width: 2048
             image_height: 256
   ```
