### ISSUE TITLE
expressions for domain id and mpi_rank

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1358]
We are adding filters for this, but in the future we want to be able do the following:

```
-
  action: "add_pipelines"
  pipelines:
    my_pipeline:
      my_expressions:
        type: "expression"
        params:
          expressions: |
            domain_id = domain_id(topology)
            rank = mpi_rank(topology)
- 
  action: "add_scenes"
  scenes: 
    my_scene: 
      plots: 
        my_plot: 
           pipeline: "my_pipeline"
           type: "pseudocolor"
           field:  "domain_id"

```

Or perhaps:

```
- 
  action: "add_scenes"
  scenes: 
    my_scene: 
      plots: 
        my_plot: 
           type: "pseudocolor"
           expression:  "mpi_rank(topology)"

```
