### ISSUE TITLE
double slice flatten extract error

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1388]
```
- 
  action: "add_pipelines"
  pipelines: 
    pl1: 
      slice_1: 
        type: "slice"
        params: 
          point: 
            x: 0.0
            y: 0.0
            z: 0.0
          normal: 
            x: 0.0
            y: 0.0
            z: 1.0
      slice_2: 
        type: "slice"
        params: 
          point: 
            x: 0.0
            y: 0.0
            z: 0.0
          normal: 
            x: 1.0
            y: 0.0
            z: 0.0
- 
  action: "add_extracts"
  extracts: 
    e1: 
      type: "flatten"
      pipeline: "pl1"
      params: 
        path: "test_out"
- 
  action: "add_scenes"
  scenes: 
    s1: 
      plots: 
        p1: 
          type: "pseudocolor"
          pipeline: "pl1"
          field: "braid"
      image_name: "out_ex"
```

```
Cannot access non-existent child "topologies" from Node([0])
```

I can render, but I can't use the flatten extract:

![Screenshot 2024-09-20 at 11 56 50 AM](https://github.com/user-attachments/assets/a114d438-e51a-497e-99d8-f58d192b8c96)
