### ISSUE TITLE
investigate nans in camera frustrum mesh

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1390]
@emily-howell  can you take a look at this case for the frustum mesh and see why nans are arriving?

```
    camera:
      position: [0.0342999994754791, 0.00480000022798777, 0.0581200011074543]
      look_at: [0.0342999994754791, 0.00480000022798777, 0.0]
      up: [0.0, 1.0, 0.0]
      zoom: 2.0
      fov: 60.0
      near_plane: 0.0363688580691814
      far_plane: 3.63688564300537
      camera_frustum_mesh:
        coordsets:
          scene_bounds_coords:
            type: "explicit"
            values:
              x: [-0.0584625, -0.0584625, -0.0584625, -0.0584625, 0.2376, 0.2376, 0.2376, 0.2376]
              y: [-0.131195885166494, -0.131195885166494, 0.0797536816207084, 0.0797536816207084, -0.131195885166494, -0.131195885166494, 0.0797536816207084, 0.0797536816207084]
              z: [0.0, 0.0108, 0.0108, 0.0, 0.0, 0.0108, 0.0108, 0.0]
          camera_frustum_coords:
            type: "explicit"
            values:
              x: ["-nan", "nan", "nan", "-nan", "-nan", "nan", "-nan", "-nan", 0.0342999994754791, 0.0342999994754791, "-nan"]
              y: ["-nan", "-nan", "-nan", "-nan", "-nan", "-nan", "-nan", "-nan", 0.00480000022798777, 0.00480000022798777, "-nan"]
              z: ["-nan", "-nan", "-nan", "-nan", "-nan", "-nan", "nan", "-nan", 0.0217511430382729, -3.57876564189792, "-nan"]
        topologies:
          scene_bounds_topo:
            type: "unstructured"
            coordset: "scene_bounds_coords"
            elements:
              shape: "line"
              connectivity: [0, 1, 1, 2, 2, 3, 3, 0, 4, 5, 5, 6, 6, 7, 7, 4, 0, 4, 1, 5, 2, 6, 3, 7]
          camera_frustum_topo:
            type: "unstructured"
            coordset: "camera_frustum_coords"
            elements:
              shape: "line"
              connectivity: [0, 1, 1, 2, 2, 3, 3, 0, 4, 5, 5, 6, 6, 7, 7, 4, 0, 4, 1, 5, 2, 6, 3, 7, 8, 9, 8, 10]
          clipping_planes_topo:
            type: "unstructured"
            coordset: "camera_frustum_coords"
            elements:
              shape: "quad"
              connectivity: [0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 5, 4, 2, 3, 7, 6, 0, 3, 7, 4, 1, 2, 6, 5]
```
