### ISSUE TITLE
add filter to combine pipeline results into a single multi-domain dataset

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1417]
interface strawman:

```
-
  action: add_pipelines
    p1:
        f1:
           ... my filter, translate dataset, etc
    p2: 
        f1:
           ... my filter, translate dataset, etc
    my_pipeline:
         pipelines: 
              - p1
              - p2
         my_filter:
               type: "combine_pipelines"
```

Considerations:
- Underlying datasets can be zero copied. 
- We will have duplicate domain ids, so domains will need to be renumbered.
