### ISSUE TITLE
World annotations / bounding box remain with Cinema render

### ISSUE THREAD

**Issue by rcarson3** [Alpine-DAV/ascent#1421]
I've been testing the cinema render feature as it seems like the best viable option that I might have while running some large simulations on the El Cap systems. I noticed if I have my renders set up like below as an example that the normal render turns off the bounding box while the Cinema still retains it while having the correct foreground and background colors. See the below pictures as well for examples of the rendered photos.

I'm currently working with Ascent v0.9.3 and VTK-m: v2.1.0 if it helps any.

```yaml
-
  action: "add_scenes"
  scenes:
    s1:
      plots: 
        p1: 
          type: "pseudocolor"
          field: "tkelv"
          color_table:
            name: "Viridis"
      renders:
        r0:
          image_prefix: "images/taylor_resolved_tkelv_%03d"
          world_annotations: "false"
          bg_color: [1.0, 1.0, 1.0]
          fg_color: [0.0, 0.0, 0.0]
        r1:
          type: "cinema"
          phi: 20
          theta: 20
          db_name: taylor_resolved_tkelv
          world_annotations: "false"
          bg_color: [1.0, 1.0, 1.0]
          fg_color: [0.0, 0.0, 0.0]
```
Render 0:
![image](https://github.com/user-attachments/assets/e849f67c-ea7d-4129-b13e-18ddf76f1576)

Render 1:
![image](https://github.com/user-attachments/assets/886b9a7a-a7ca-468b-98f9-66bb2e601c6e)
