### ISSUE TITLE
compact color table args

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1436]
Current color table args format:
```
          color_table: 
            name: "blue"
            control_points: 
              - 
                type: "rgb"
                position: 0.0
                color: [1.0, 0.0, 0.0]
              - 
                type: "rgb"
                position: 0.5
                color: [0.0, 1.0, 0.0]
              - 
                type: "rgb"
                position: 1.0
                color: [1.0, 1.0, 1.0]
              - 
                type: "alpha"
                position: 0.0
                alpha: 0.0
              - 
                type: "alpha"
                position: 1.0
                alpha: 1.0
```

also, support suggested compact color table args format:
```
          color_table: 
            name: "blue"
            control_points: 
               r: [1.0, 0.0, 1.0]
               g: [0.0, 1.0, 1.0]
               b: [0.0, 0.0, 1.0]
               a: [0.0, 0.5, 1.0]
               position: [ 0.0, 0.5, 1.0]
```
