### ISSUE TITLE
sampling interface additions

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1449]
For uniform grid: 
- Allow spatial extents to be specified as an alternative to `origin` and `spacing`. This from will be more natural for many use cases
- Allow `fields` in addition to `field`, and support sampling multiple fields.

**Comment by cyrush** [comment]
Expand sampling cases beyond uniform grids, with a generic "sample" filter.

We should provide an interface that mirrors clip (perhaps expanded to also include the seed patterns in the streamline filter)

- box (this basically is our uniform grid filter)
- line (not in clip, but perhaps should be) 
- plane
- sphere
- cylinder
- mesh: allow users to provide a blueprint mesh to sample onto

Like current sampling - start with results only on rank 0 (this is the most pressing use case)

**Comment by cyrush** [comment]
@nicolemarsaglia I updated this ticket with ideas about expanding how we leverage sampling to provide users more options.

**Comment by cyrush** [comment]
Box Cases:

```
type: "sample"
params: 
          field: "den"
          # or fields: ["den", "temp"]
          box:
            dims:
              i: 1500
              j: 500
            origin:
              x: 0.0
              y: 0.0
            spacing:
              dx: .01
              dy: .01 
```
```
type: "sample"
params: 
          field: "den"
          # or fields: ["den", "temp"]
          box:
            dims:
              i: 1500
              j: 500
            min:
               x: 0.0
               y: 0.0
            max:
               x: 100
               y: 100
```

Line case:
```
type: "sample"
params: 
          field: "den"
          # or fields: ["den", "temp"]
          line:
            samples: 100
            start:
               x: 0.0
               y: 0.0
            end:
               x: 100
               y: 100
```

Points case:
```
type: "sample"
params: 
          field: "den"
          # or fields: ["den", "temp"]
          points:
            x: [ x0, x1, x2, ... ]
            y: [ x0, x1, x2, ... ]
```
