### ISSUE TITLE
dray renders missing chunks

### ISSUE THREAD

**Issue by emily-howell** [Alpine-DAV/ascent#1462]
I am new to Devil Ray rendering so it is quite possible that I don't have the right setting enabled. However, when trying to plot a simple braid example, I found that chunks of the plots were not rendering. 

The actions look like:
```
- 
  action: "add_extracts"
  extracts: 
    e1: 
      type: "dray_pseudocolor"
      params: 
        field: "braid"
        color_table: 
          control_points: 
            r: [0.23, 0.48, 0.99]
            g: [0.08, 0.23, 1.0]
            b: [0.08, 0.04, 0.96]
            a: [1.0, 1.0, 1.0]
            position: [0.0, 0.5, 1.0]
        image_width: 512
        image_height: 512
        image_prefix: "/path/.../dray_compressed_color_table"
```

Example 1:
![Image](https://github.com/user-attachments/assets/d729aec2-1912-43ea-9f2b-3aae7e96fcb2)

Example 2:
![Image](https://github.com/user-attachments/assets/afd25454-4d10-41eb-aba3-fd004a693a5e)

When plotting with VTKM, this was the desired result:
![Image](https://github.com/user-attachments/assets/7d657f38-4579-4fa0-8667-3c66396aaff8)
