### ISSUE TITLE
info is missing extract file path for relay extract

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1465]
```
- 
  action: "add_extracts"
  extracts: 
    e1: 
      type: "relay"

      params: 
        path: "out_export_braid_all_fields"
        protocol: "blueprint/mesh/hdf5"
```

Resulting info:

```
- 
  type: "relay"
  protocol: "blueprint/mesh/hdf5"
  path: ""
```
