### ISSUE TITLE
camera improvements for 2d use cases 

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1479]
Camera info does not show 2d mode params and we should add an explicit 2d mode camera.

If you have a 2d dataset with no camera specified, you get a 2D style camera.

However, all camera params we currently accept are 3d, if you provide any camera you are back in 3D mode.

**Comment by cyrush** [comment]
3d Camera:

```
    camera: 
      position: [-8.88178419700125e-16, -8.88178419700125e-16, 28.2842712402344]
      look_at: [-8.88178419700125e-16, -8.88178419700125e-16, 0.0]
      up: [0.0, 1.0, 0.0]
      zoom: 1.0
      fov: 60.0
      near_plane: 2.82842707633972
      far_plane: 282.842712402344
```

This info is missing `xpan`, `ypan` (note: `zoom` is effectively `zpan`)
We could also add the projection and view matrix info, but we can't directly set those in VTK-m.

Proposed 2d Camera Input Spec:

```
  camera: 
    2d: [l,r,b,t]
```

or more verbose:

```
  camera: 
    2d:
       left: l
       right: r
       bottom: b
       top: t
```
