### ISSUE TITLE
z culling issue with small mesh extends in large view

### ISSUE THREAD

**Issue by mlohry** [Alpine-DAV/ascent#1490]
Using the example mesh `conduit::blueprint::mesh::examples::braid("mixed", 16, 16, 16, mesh);`
and attempting to render results in the error:
```
message: 
Shape Map Entries do not match required VTK-m Shape Ids.
Passed Shape Map:

polyhedral: 42
tet: 10
hex: 12

Supported Shape Map:

tri: 5
quad: 9
tet: 10
hex: 12
point: 1
line: 3
wedge: 13
pyramid: 14
```

i.e. the polyhedral type looks unsupported, at least when mixed with standard shapes.

Exporting the HDF5 for this and trying to load in visit also hits an error when trying to load/render the mesh:

```
The compute engine running on lancer has exited abnormally.

Shortly thereafter, the following occured...

The Mesh plot of "mesh_mesh" for the file "all_output_braid.cycle_000100.root" could not be generated by the compute engine on host "localhost".
```

braid with all tets or other element types works as expected.

**Comment by JustinPrivitera** [comment]
I can't speak authoritatively on what the issue might be in Ascent, but in VisIt we added mixed element topology support to the Blueprint reader in our latest release, 3.4.2. Which version of VisIt were you using when you saw the error?

**Comment by mlohry** [comment]
Thanks @JustinPrivitera , visit 3.4.2 works; I was on 3.4.1 which didn't.

So the braid example containing polyhedra fails in the ascent render with the original error. A different mixed element mesh without polyhedra looks like it works correctly, except that sliced fields show blank images.

**Comment by JustinPrivitera** [comment]
I can confirm that we do not yet support polyhedral mixed topologies in Ascent. We may look to add that support in a future release, but not the most imminent release which is coming shortly.

**Comment by mlohry** [comment]
The main mixed element case I'm interested in doesn't have polyhedral elements. This example is comprised of tet, pyramid, and wedge. I can render a field on the full mesh correctly:

![Image](https://github.com/user-attachments/assets/670b204c-af69-44d4-9e6d-d5301f3f5ba4)

And I can show a mesh on a slice pipeline correctly:

![Image](https://github.com/user-attachments/assets/8255e0d0-8201-4465-ae1d-bbe8d8b8eb4a)

but the same setup for the field renders a blank black screen (or the mesh+black if i also add the mesh)

![Image](https://github.com/user-attachments/assets/5a1f046a-7cf2-41f0-a20e-16d2dca2bc85)

**Comment by nicolemarsaglia** [comment]
Hmm odd. @mlohry could you share an extract and your actions file?

**Comment by mlohry** [comment]
[out_hdf5.root.zip](https://github.com/user-attachments/files/19435961/out_hdf5.root.zip)


```
-
  action: "add_pipelines"
  pipelines:
    pl1:
      f1:
        type: "slice"
        params:
          point:
            x: 0.0
            y: 468.75
            z: 0.0
          normal:
            x: 0.0
            y: 1.0
            z: 0.0
- 
  action: "add_scenes"
  scenes: 
    s1: 
      plots:
        p1: 
          type: "pseudocolor"
          field: "test_field"
      renders:
        default_view:
          image_width: 1024
          image_height: 1024
          image_prefix: "render_full_mesh"
    s2: 
      plots: 
        p1: 
          type: "mesh"
          pipeline: "pl1"
      renders:
        r1:
          image_width: 1024
          image_height: 1024
          image_prefix: "render_slice_mesh"
          world_annotations: "true"
          annotations: "true"
          camera:
            position: [1325.90, -700.0, 177.95]
            look_at: [1325.90, 468.75, 177.95]
            up: [0.0, 0.0, 1.0]
    s3: 
      plots: 
        p1: 
          type: "pseudocolor"
          pipeline: "pl1"
          field: "test_field"
      renders:
        r1:
          image_width: 1024
          image_height: 1024
          image_prefix: "render_slice_field"
          world_annotations: "true"
          annotations: "true"
          camera:
            position: [1325.90, -700.0, 177.95]
            look_at: [1325.90, 468.75, 177.95]
            up: [0.0, 0.0, 1.0]
- 
  action: "add_extracts"
  extracts:
    e1:
      type: "relay"
      params:
        path: "all_output"
        protocol: "blueprint/mesh/hdf5"
```
