### ISSUE TITLE
report of queries undermining extracts

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1493]
```
-
  action: "add_queries"
  queries:
    q1:
      params:
        expression:  lineout(10000, vector(-10,0,0), vector(30,0,0), fields=[myfield], empty_val=-1.0)
        name: "lineout"
-
  action: "add_extracts"
  extracts:
    e1:
      type: "python"
      params:
        src: "test.py"
```

Even though the extract is not wired up to the queries at all, they may be crossed.
