### ISSUE TITLE
project_2d + extract keeps extra topology data

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1503]
use case:

multiple topos, apply project_2d to one of them, use relay extract and only select the project_2d result topo.
Seems the other topo data is still saved.

Need to solve this mystery

**Comment by cyrush** [comment]
I have an extract with multiple topologies and I cannot replicate the issue with replay.

Here is a working set of actions:

```
- action: "declare_fields"
  fields: ["density"]
- 
  action: "add_pipelines"
  pipelines: 
    my_scalar_render_pipeline: 
      scalar_render: 
        type: "project_2d"
        params: 
          topology: main
          image_width: 1500
          image_height: 500
          fields: ["density"]
- 
  action: "add_extracts"
  extracts:
    e1:
      type: "relay"
      pipeline: my_scalar_render_pipeline
      params:
        protocol: hdf5
        path: tout_my_ext_res

```

Note: `density` is defined on the topology `main`, so it a surprise i also have to specify `topology: main`
