### ISSUE TITLE
Duplicate mesh without copying data

### ISSUE THREAD

**Issue by FrankFrank9** [Alpine-DAV/ascent#1532]
Hi is there such a functionality in ascent?

https://discourse.paraview.org/t/duplicate-object-in-view/14706

Best,

**Comment by cyrush** [comment]
You have to use a pipeline with a transform filter to translate.

But this isn't instancing for a view -- it will end up making a copy. We don't have a way to alias a mesh and then translate just for rendering. 

Depending on how you want to setup the scene, you can reduce the impact of copy by using an external surfaces filter before you translate.

**Comment by FrankFrank9** [comment]
Hi @cyrush,

thanks a lot for the hint.

Do you have a MWE as yaml for this?

Best,

**Comment by cyrush** [comment]
Here is an example:

```
- 
  action: "add_pipelines"
  pipelines: 
    pl_ext_surfaces: 
      f1: 
        type: "external_surfaces"
    pl_translate_plus: 
      f1: 
        type: "transform"
        params: 
          translate: 
            x: 25.0
            y: 25.0
    pl_translate_minus: 
      f1: 
        type: "transform"
        params: 
          translate: 
            x: -25.0
            y: -25.0
- 
  action: "add_scenes"
  scenes: 
    s1: 
      plots: 
        p1: 
          type: "pseudocolor"
          field: "braid"
          pipeline: "pl_ext_surfaces"
        p2: 
          type: "pseudocolor"
          field: "braid"
          pipeline: "pl_translate_minus"
        p3: 
          type: "pseudocolor"
          field: "braid"
          pipeline: "pl_translate_plus"
      renders: 
        r1: 
          camera: 
            azimuth: 35
          image_prefix: "tout_external_surfaces_3d_multi_pipeline_render"
```

**Comment by FrankFrank9** [comment]
Hi @cyrush,

thanks a lot. I gave it a try but it is too memory intensive for my case.

You can close this issue or turn it into a feature request for future releases.

Thanks again for the prompt help.

Best,

**Comment by cyrush** [comment]
No worries thanks for trying out this possible approach and for the feedback.

**Comment by FrankFrank9** [comment]
Hi @cyrush 

to reduce computational cost I was trying to translate the result of a pipeline itself
The MWE yaml is:

```

- 
  action: "add_scenes"
  scenes: 
    s_q1: 
      plots: 
        p1: 
          type: "pseudocolor"
          field: "omegaznd"
          pipeline: "pl_qup"
          color_table: 
            name: "Cool to Warm"
          min_value: -20
          max_value: 20
        p2: 
          type: "pseudocolor"
          field: "schlieren"
          pipeline: "pl_sliceup"
          color_table: 
            name: "X Ray"
          min_value: 0
          max_value: 25
        p3: 
          type: "pseudocolor"
          field: "omegaznd"
          pipeline: "pl_qdwn"
          color_table: 
            name: "Cool to Warm"
          min_value: -20
          max_value: 20
        p4: 
          type: "pseudocolor"
          field: "schlieren"
          pipeline: "pl_slicedwn"
          color_table: 
            name: "X Ray"
          min_value: 0
          max_value: 25
      renders: 
        r_1: 
          fg_color: [0.0, 0.0, 0.0]
          image_width: 3840
          image_height: 2160
          camera: 
            zoom: 2.0
            position: [0.04921617, -0.02423519, 0.15830382]
            look_at: [0.04921617, -0.02423519, 0.0054]
            up: [0.0, 1.0, 0.0]
          render_bg: "false"
          world_annotations: "false"
          color_bar_position: [2.0, 2.0, 2.0, 2.0]
- 
  action: "add_pipelines"
  pipelines: 
    pl_q: 
      f0: 
        type: "qcriterion"
        params: 
          field: "velocity"
          output_name: "q"
      f1: 
        type: "contour"
        params: 
          field: "q"
          iso_values: 100.0
    pl_qup: 
      pipeline: "pl_q"
      f0: 
        type: "transform"
        params: 
          translate: 
            x: 0.0
            y: 0.0396
            z: 0.0
    pl_qdwn: 
      pipeline: "pl_q"
      f0: 
        type: "transform"
        params: 
          translate: 
            x: 0.0
            y: -0.0396
            z: 0.0
    pl_slice: 
      f1: 
        type: "slice"
        params: 
          point: 
            x: 0.0
            y: 0.0
            z: 0.0054
          normal: 
            x: 0.0
            y: 0.0
            z: 1.0
- 
  action: "add_extracts"
  extracts: 
- 
  action: "add_queries"
  queries: 

```

but then I get the error:

```
[Error] Ascent::execute 
file: /ascent/build/ascent/src/libs/ascent/runtimes/ascent_main_runtime.cpp
line: 898
message: 
Unrecognized transform filter transform
```

Where is my mistake? Is it allowed to translate only pipelines results?
