### ISSUE TITLE
Multiple pipelines results in one visualization

### ISSUE THREAD

**Issue by FrankFrank9** [Alpine-DAV/ascent#1533]
Hi,

I was wondring if it is possible in ascent to combine multiple pipelines into a single visualization.
For example I would like to get a pipeline that performs a slicing and pseudcolor operation and overlay this results with a pipeline that performs a qcontour and isocontour visualization.

For example using something similar for the slice 

`#An example of the slice filter with a single plane.

- 
  action: "add_pipelines"
  pipelines: 
    pl1: 
      f1: 
        type: "exaslice"
        params: 
          point: 
            x: 0.0
            y: 0.0
            z: 0.0
          normal: 
            x: 0.0
            y: 0.0
            z: 1.0
- 
  action: "add_scenes"
  scenes: 
    s1: 
      plots: 
        p1: 
          type: "pseudocolor"
          field: "radial"
          pipeline: "pl1"
      image_prefix: "/Users/harrison37/Work/alpine/ascent/build-debug/tests/_output/tout_exaslice_3d"`

and something similar for the qcriterion

- 
  action: "add_pipelines"
  pipelines: 
    pl1: 
      f2: 
        type: "qcriterion"
        params: 
          field: "vel"
          output_name: "vel_qcriterion"
          use_cell_gradient: "false"
- 
  action: "add_scenes"
  scenes: 
    s1: 
      plots: 
        p1: 
          type: "pseudocolor"
          field: "vel_qcriterion"
          pipeline: "pl1"
      image_prefix: "/Users/harrison37/Work/alpine/ascent/build-debug/tests/_output/tout_qcriterion_vel"

But then visualize both pipelines into one single scene

I do apologize if such a feature is documented but I was unable to find it.

Best

**Comment by cyrush** [comment]
@FrankFrank9  Yes, ascent supports this. 

The key is to have uniquely named pipelines and then in your scene, add two plots. Each plot can select a pipeline and all the plots will be rendered together. 

Here is an example to get you started:

```
- action: add_pipelines
  pipelines:
    my_slice_pl:
      f1:
        type: exaslice
        params:
          point:
            x: 0
            y: 0
            z: 0
          normal:
            x: 0
            y: 0
            z: 1
    my_qcrit_pl:
      f2:
        type: qcriterion
        params:
          field: vel
          output_name: vel_qcriterion
          use_cell_gradient: "false"
- action: add_scenes
  scenes:
    s1:
      image_prefix: "tout_both_plots"
      plots:
        p_slice:
          type: pseudocolor
          field: radial
          pipeline: my_slice_pl
        p_qcrit:
          type: pseudocolor
          field: vel_qcriterion
          pipeline: my_qcrit_pl

```
