### ISSUE TITLE
background color is reset when rendering mesh

### ISSUE THREAD

**Issue by yslan** [Alpine-DAV/ascent#1557]
I have the same set of images plotting in white background just fine.
When I add one extra plot for showing mesh, the background changed back to black again.

```
-
  action: "add_scenes"
  scenes:
...
    s4:
      plots:
...
        p6:
          type: "mesh"
          pipeline: "pl5"
      renders:  
        r1:
          camera:
            position: [88.0, 88.0, 95.0]
            look_at: [0.0, 0.0, 0.0]
            up: [0.0, 0.0, 1.0]
            zoom: 2.5
          image_prefix: "imgs/ann_msh2_%06d"

          # below is the same as the other image
          world_annotations: false
          screen_annotations: false
          bg_color: [1.0, 1.0, 1.0]
          fg_color: [0.0, 0.0, 0.0]
          image_width: 4096
          image_height: 4096
```

**Version**
```
---------------- Ascent.about() ----------------
version: "0.9.3-6a97a-dirty"
git_sha1: "6a97a70974b377c60b177162af2e6f3d3c1f63e7-dirty"
install_prefix: "/soft/visualization/ascent/develop/2025-03-19-c1f63e7-openmp/ascent-checkout"
```
