### ISSUE TITLE
Ascent v0.9.3 extract missing cycle string

### ISSUE THREAD

**Issue by timohyva** [Alpine-DAV/ascent#1564]
I am using `v0.9.3` on Cray AMD GPU system to output hdf5 files. In the older version of Ascent like `v0.9.0`, `extract` output files names are automatically suffixed with `.cycle-xxxx.root`. However, `v0.9.3` can't do this any more with old setup, and cause overwriting of hdf5 files. I wonder if one can achieve similar effect or preventing hdf5 overwriting without recompiling Ascent? For example, add some parameters for `extract` or `hdf5_option`? 

After reading issue [#1285](https://github.com/Alpine-DAV/ascent/issues/1285), I know new feature about this has been developed for `v0.9.4`, but it is released yet. What to do in this situation?

**Comment by cyrush** [comment]
@timohyva  The cycle suffix should not have changed between 0.9.0 and 0.9.3.
Can you double check you are providing the cycle as part of the state in your tests with 0.9.3?

**Comment by timohyva** [comment]
> [@timohyva](https://github.com/timohyva) The cycle suffix should not have changed between 0.9.0 and 0.9.3. Can you double check you are providing the cycle as part of the state in your tests with 0.9.3?

Hi, @cyrush , thank you for replying. here is what in my action for `extract`:
```C++
conduit::Node &add_act5 = actions.append();
add_act5["action"] = "add_extracts";
conduit::Node &extracts = add_act5["extracts"]; 
extracts["e1/type"] = "relay"; 
extracts["e1/params/path"] = "sim-data";
extracts["e1/params/protocol"] = "blueprint/mesh/hdf5";
```
What exactly your meaning of "providing the cycle as part of the state"? I tried putting `sim-data-{cycle:%06d}` for `extracts["e1/params/path"] ` , but I just got "sim-data-{cycle:%06d}.root" without `cyclexxx`.

**Comment by timohyva** [comment]
> are providing the cycle

here is `yml` output:
```shell
  action: "add_extracts"
  extracts: 
    e1: 
      type: "relay"
      params: 
        path: "sim-data"
        protocol: "hdf5"
        fields:
           ....
```
any missing info for providing `cycle`?

**Comment by cyrush** [comment]
For the data provided via `ascent::publish`, each domain should include:

```
state:
 cycle: 1
```

**Comment by timohyva** [comment]
> For the data provided via `ascent::publish`, each domain should include:
> 
> ```
> state:
>  cycle: 1
> ```

ahaa, surely I don't have this in `yml` outout, I think this is the problem.
How to access this string? where should I assign `1` or `true` for this?

**Comment by timohyva** [comment]
> > For the data provided via `ascent::publish`, each domain should include:
> > ```
> > state:
> >  cycle: 1
> > ```
> 
> ahaa, surely I don't have this in `yml` outout, I think this is the problem. How to access this string? where should I assign `1` or `true` for this?



> For the data provided via `ascent::publish`, each domain should include:
> 
> ```
> state:
>  cycle: 1
> ```

I think I just need to add `mesh["state/cycle"] = "true"` in to mesh.
I noticed that `state` doesn't output in stand output, but only `filter` and `scene`. How to make mesh state also be output?

**Comment by cyrush** [comment]
The value should be the cycle number, which should be unique each time you publish.

Here is an example mesh:

```

state: 
  time: 3.1415
  cycle: 100
coordsets: 
  coords: 
    type: "explicit"
    values: 
      x: [-10.0, -7.77777777777778, -5.55555555555556, ..., 7.77777777777778, 10.0]
      y: [-10.0, -10.0, -10.0, ..., 10.0, 10.0]
topologies: 
  mesh: 
    type: "unstructured"
    coordset: "coords"
    elements: 
      shape: "quad"
      connectivity: [0, 10, 11, ..., 99, 89]
fields: 
  braid: 
    association: "vertex"
    topology: "mesh"
    values: [2.00961335163232, 3.88120226592316, 1.00778352270287, ..., 0.0915677318528372, -0.814562706228405]
  radial: 
    association: "element"
    topology: "mesh"
    values: [141.42135623731, 126.686158344349, 114.395890455411, ..., 95.5813918560292, 109.994388184574]
  vel: 
    association: "vertex"
    topology: "mesh"
    values: 
      u: [-10.0, -7.77777777777778, -5.55555555555556, ..., 7.77777777777778, 10.0]
      v: [-10.0, -10.0, -10.0, ..., 10.0, 10.0]
```

Let me know of this helps
