### ISSUE TITLE
add additional surprise checking for actions scenes/filters/

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/ascent#421]
We currently check for surprises in filter parameters, but not in higher level stuff.

**Comment by mclarsen** [comment]
Here is an example:
```
- 
  pipelines: 
    pipe1: 
      f0: 
        params: 
          bins: "32"
          field: energy
          sample_rate: "0.05"
        type: histsampling
```
Generates:
```
[Error] Ascent::execute 
file: /global/u2/h/hazarika/projects/ALPINE_WORKFLOW/ascent/build/spack/var/spack/stage/spack-stage-conduit-develop-urrx5p6alo3c7rdfaza5mienalxjooid/spack-src/src/libs/conduit/conduit_node.cpp
line: 12940
message: 
Cannot access non-existent child "action" from Node([0])
```
