### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/ascent#478]
What we need to keep

- History is indexed by cycle in an hdf5 file
- Info node (queries, images(cameras), actions, graph)
    - Restart: only show changes to actions
    - What did I do (resolved actions)
        - Vtkh have a way to report things (have methods for what levels it chose or scalar range it used)
- What did we see in publish?
    - Original bounds
    - Original scalar range
    - Just calculate when published(architect??) 
    - Create vector mag-> do->add_field adds info to meta data
- How many files do we use (one file multiple hdf5 trees)?
    - Expressions files (read in everytime)
   - Resolved actions (never read back in)
        - Replay can use resolved actions
        - Tool to extract new yaml actions files based on what it did
- When do we write: on ascent::close()

**Comment by mclarsen** [comment]
Potential output for a filter:
```
filter_name: "pl1_0_vtkh_marchingcubes"
filter_type: "vtkh_marchingcubes"
params: 
  field: "braid"
  iso_values: [-0.4, 0.2, 0.4]
```
So in this case, there were three levels and the resulting iso values are shown above. Do we need to keep track of the levels or use contour tree? Saying it another way, levels is magic that gets translated into what the filter actually does, so do we store what we did and that magic used to create it or just what we did?

What other information do we need to keep track of?

**Comment by mlohry** [comment]
I'm not sure if it's related to this enhancement, but is there a way to programmatically determine what, if any, files have been written after an `Ascent::execute` call, without resorting to checking the filesystem directly?

**Comment by cyrush** [comment]
@mlohry  

Check out the results you can get from `Ascent::info()` under `images`, here is an example:

```
images: 
  - 
    image_name: "out_scene_ex1_render_var1.png"
    image_width: 1024
    image_height: 1024
    camera: 
      position: [0.0, 0.0, 3.5]
      look_at: [0.0, 0.0, 0.5]
      up: [0.0, 1.0, 0.0]
      zoom: 1.0
      fov: 60.0
    scene_bounds: [-1.0, -1.0, 0.0, 1.0, 1.0, 1.0]
  - 
    image_name: "out_scene_ex1_render_var2.png"
    image_width: 1024
    image_height: 1024
    camera: 
      position: [0.0, 0.0, 3.5]
      look_at: [0.0, 0.0, 0.5]
      up: [0.0, 1.0, 0.0]
      zoom: 1.0
      fov: 60.0
    scene_bounds: [-1.0, -1.0, 0.0, 1.0, 1.0, 1.0]
```

There will be entries for every image rendered.
