### ISSUE TITLE
problem of building ascent//src/examples/proxies/lulesh2.0.3

### ISSUE THREAD

**Issue by IAMkecheng** [Alpine-DAV/ascent#531]
I have run the example under ascent/build/ascent-install/examples/ascent/proxies/lulesh successfully, but the generated figures are all the same except the value range:
![image](https://user-images.githubusercontent.com/12473275/84148946-4783f980-aa92-11ea-8c08-4c696f152891.png)

And when I tried to compile the project source file that under ascent//src/examples/proxies/lulesh2.0.3, after make there was nothing generated, is there anything missed in the CMakelist.txt, or what should I do to fix this problem?

**Comment by mclarsen** [comment]
Lulesh deposits energy in one corner of the data set and the shockwave propagates radially.  Unfortunately, that region is on then other side of the data set.

We have example actions that show you how to manipulate the camera:
https://ascent.readthedocs.io/en/latest/Actions/Examples.html

We can adjust the camera to look at the other side.
```
- 
  action: "add_scenes"
  scenes: 
    s1: 
      plots: 
        p1: 
          type: "pseudocolor"
          field: "e"
      renders: 
        r1: 
          image_prefix: "energy_image"
          camera:
            azimuth: 180
```
Azimuth will swing the camera around. Apologies if I got the indentation wrong.

Re make problem: I think I am missing some infomation. What directory did you try to make in?
