### ISSUE TITLE
WarpX todos and feature requests

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/ascent#639]
- [x] - fix: ascent_action aborts if a pipeline contains a species that for a certain time step has zero particles
- [ ] - fix: error throw by volume compositing (inside diy) when there are no pixels
- [x] - fix: besides position, particle properties are broken (i.e. the SoA real ones).
- [ ] - relax limitation: changing the 3D aspect ratio of all meshes and particles at once (fixed, i.e. coordinate_aspect_ratio(1.0, 1.0, 1.5) and relative, i.e. coordinate_aspect_squeeze(1.0, 1.0, 0.05), will both have their use-cases; fixed will be needed more often)
- [ ] - relax limitation: only one volume rendering can be used at a time
- [ ] - RFE: exposing light/shadow maps
- [ ] - RFE: semi-transparent iso-contours
- [ ] - RFE: option to smooth iso-contours surfaces at low resolutions
- [ ] - RFE: printf-formatting of axis and color-bar labels
- [ ] - RFE: add filter to change the coordinate system to an arbitrary set of fields

Currently we bend the inputs of WarpX and hack the code base to work around the first four points.
The last four points is what we usually do in post-processing and would give us more creative freedom, e.g. for the discussed "slow but pretty" rendering.
All points are in-order of how they would make the greatest impact for us.

@ax3l

**Comment by ax3l** [comment]
cross-ref: last point is #638

Python string or [fmt string](https://github.com/fmtlib/fmt) would be prefered over an old-school C-ish printf string

**Comment by ax3l** [comment]
detail on first point: seen with a pipeline that uses `histsampling`:
```yaml
    sampled_particles:
      f1:
        type: histsampling
        params:
          field: particle_electrons_uz # this source has zero entries in some time steps
          bins: 64
          sample_rate: 0.90
```
