### ISSUE TITLE
error using dray_vector_component with lineout

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#863]
goal: do a lineout with a component from a vector field:

actions:

```
-
  action: "add_pipelines"
  pipelines:
    pl1:
      f1:
        type: "dray_vector_component"
        params:
          field: "velocity"
          component: 0
          output_name: "velocity_x"
-
  action: "add_queries"
  queries:
    q1:
      params:
        expression: "lineout(2560,vector(0,0,0),vector(128,0,0), fields=['density','velocity_x'], empty_val=-1.0)"
        name: "lineouts"
      pipeline: "pl1"
```

result:

```
[INFO]: Ascent execute actions file: ascent_actions.yaml
[Error] Ascent::execute 
file: src/ascent/runtimes/ascent_data_object.cpp
line: 410
message: 
this should never happen
```

the data object is confused, perhaps we need some logic to handle flipping back and forth between reps (bp and dray) that isn't wired up when we add the new field.
