### ISSUE TITLE
Blueprint verify failed: published data is empty

### ISSUE THREAD

**Issue by mdorier** [Alpine-DAV/ascent#956]
I'm new to Ascent. I'm trying to use it with the AMR-WIND application, but I'm getting an error when calling `Ascent::execute`:

```
[Error] Ascent::execute
file: /tmp/mdorier/spack-stage/spack-stage-ascent-0.8.0-eqfd4qf6lknbsf3orpcs6w3vl43fcnlt/spack-src/src/ascent/runtimes/flow_filters/ascent_runtime_blueprint_filters.cpp
line: 171
message:
blueprint verify failed: published data is empty
```

I can confirm that the node I pass to `ascent.publish()` prior to calling `execute` does have data: if I serialize the node into json and write it in a file I can see a bunch of domains in the form "domain_XXXXXX". These domains include, among other things, a "fields" section, which contains three sections: "velocityx", "velocityy", and "velocityz", which include values.

I'm passing an empty (default-constructed) `conduit::Node` to `execute`, but I have opened Ascent with an option node that contains an `"actions_file"` field. I can confirm that Ascent finds it because it complains if I set the file name to something that doesn't exist.

The actions file I'm using is the following:

```yaml
-
  action: "add_pipelines"
  pipelines:
    pl1:
      f1:
        type: "composite_vector"
        params:
          field1: "velocityx"
          field2: "velocityy"
          field3: "velocityz"
          output_name: "velocity"
      f2:
        type: "vector_magnitude"
        params:
          field: "velocity"
          output_name: "magnitude"
-
  action: "add_scenes"
  scenes:
    s1:
      plots:
        p1:
          type: "pseudocolor"
          field: "magnitude"
          pipeline: "pl1"
```

My understanding is that Ascent should take the `velocity{x,y,z}` fields and produce a `velocity` vector field, then produce a `magnitude` field containing the magnitude of this vector, and finally do a pseudocolor plot of this magnitude. I'm lost as to why Ascent is complaining about empty data being published... any ideas?
